(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='bb_admin_hash_v5', GH='bb_gh_v5'; let ps=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const b64=s=>btoa(unescape(encodeURIComponent(s)));
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function msg(id,t,ok=false){const e=$(id);if(e){e.textContent=t;e.className='form-msg '+(ok?'ok':'')}}
function gh(){try{return JSON.parse(sessionStorage.getItem(GH)||'{}')}catch{return {}}}
function getG(){const g=gh();return{user:$('#ghUser').value.trim()||g.user||'',repo:$('#ghRepo').value.trim()||g.repo||'',token:$('#ghToken').value.trim()||g.token||'',branch:$('#ghBranch').value.trim()||g.branch||'main'}}
function saveG(){const g=getG();sessionStorage.setItem(GH,JSON.stringify(g));return g}
async function api(path,opts={}){
 const g=getG();
 if(!g.user||!g.repo||!g.token)throw Error('GitHub API নেই: Username, Repository, Token এবং Branch পূরণ করুন।');
 const url='https://api.github.com/repos/'+encodeURIComponent(g.user)+'/'+encodeURIComponent(g.repo)+'/contents/'+path;
 const r=await fetch(url,{...opts,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+g.token,'Content-Type':'application/json'}});
 if(!r.ok){let tx='';try{tx=await r.text()}catch{};throw Error(`GitHub API ${r.status}: ${tx.slice(0,220)}`)}
 return r.json();
}
async function put(path,content,commit){
 let old=null;try{old=await api(path)}catch(e){if(!String(e.message).includes('GitHub API 404'))throw e}
 const body={message:commit,content:b64(content),branch:getG().branch};if(old?.sha)body.sha=old.sha;
 return api(path,{method:'PUT',body:JSON.stringify(body)});
}
function defaultSite(){return{version:5,name:'BanglaBazar',logo:'',favicon:'',primary:'#1769d1',button:'#1769d1',buttonText:'#ffffff',background:'#f6f8fb',card:'#ffffff',text:'#17212b',muted:'#6b7685',border:'#e3e8ef',currency:'৳',deliveryFee:60,showPrices:true,heroTitle:'BanglaBazar',heroText:'পছন্দের পণ্য সহজেই খুঁজুন এবং কার্টে যোগ করুন।',heroEyebrow:'আপনার অনলাইন শপ',heroImage:'',announcement:'',footerText:'বিশ্বস্ত অনলাইন শপ',contactPhone:'01949737370',whatsapp:'8801949737370',facebook:'',instagram:'',youtube:'',showCategories:true,showRelated:true,showReviews:true,showVideos:true,showWishlist:true,showCart:true,showSearch:true,seoTitle:'BanglaBazar — আপনার অনলাইন শপ',seoDescription:'BanglaBazar অনলাইন শপ।'}}
async function readSite(){try{const r=await fetch('data/site.json?v='+Date.now(),{cache:'no-store'});return r.ok?{...defaultSite(),...await r.json()}:defaultSite()}catch{return defaultSite()}}
async function loadProducts(){try{const r=await fetch('data/products.json?v='+Date.now(),{cache:'no-store'});const j=await r.json();ps=j.products||[]}catch{ps=[]}$('#adminProductList').innerHTML=ps.map(p=>`<div class="admin-product"><div class="admin-thumb">${p.image?`<img src="${esc(p.image)}" alt="">`:'B'}</div><div><b>${esc(p.title)}</b><span>${esc(p.id)} · ${esc(p.category||'')}</span></div><button data-edit="${esc(p.id)}">${icon('edit')} Edit</button></div>`).join('')||'<div class="empty">কোনো পণ্য নেই।</div>';$('#statProducts').textContent=ps.length;$('#statCategories').textContent=new Set(ps.map(p=>p.category).filter(Boolean)).size}
async function testGithub(){try{const g=getG();if(!g.user||!g.repo||!g.token)throw Error('সব GitHub তথ্য দিন।');const r=await api('');$('#repoInfo').textContent=r.full_name||g.user+'/'+g.repo;$('#ghStatus').textContent='GitHub connection সফল।';msg('#adminMsg','GitHub API connection সফল।',true)}catch(e){msg('#adminMsg',e.message)}}
function collectProduct(){let id=$('#pId').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,'');return{id,slug:id,title:$('#pTitle').value.trim(),category:$('#pCategory').value.trim(),brand:$('#pBrand').value.trim(),sku:$('#pSku').value.trim(),price:Number($('#pPrice').value||0),oldPrice:Number($('#pOldPrice').value||0),stock:Number($('#pStock').value||0),status:$('#pStatus').value,shortDescription:$('#pShort').value.trim(),image:$('#pImage').value.trim(),images:$('#pImages').value.split('\n').map(x=>x.trim()).filter(Boolean),youtube:$('#pYoutube').value.split('\n').map(x=>x.trim()).filter(Boolean),tags:$('#pTags').value.split(',').map(x=>x.trim()).filter(Boolean),description:'content/'+id+'.md'}}
async function publish(e){e.preventDefault();try{const p=collectProduct();if(!p.id||!p.title)throw Error('Product ID/slug এবং Product Name দিন।');if(!/^[a-z0-9-]+$/.test(p.id))throw Error('Product ID শুধু English letters, numbers এবং hyphen হবে।');if(!getG().token)throw Error('GitHub API Token নেই। Admin login-এর GitHub fields পূরণ করুন।');const r=await fetch('data/products.json?v='+Date.now(),{cache:'no-store'});const data=await r.json();const arr=(data.products||[]).filter(x=>x.id!==p.id);arr.push(p);await put('data/products.json',JSON.stringify({version:5,products:arr},null,2),'Update product '+p.id);await put('content/'+p.id+'.md',$('#pDescription').value,'Update description '+p.id);const tr=await fetch('products/product-template.html?v='+Date.now(),{cache:'no-store'});if(!tr.ok)throw Error('Product template পাওয়া যায়নি।');const template=await tr.text();await put('products/'+p.id+'.html',template,'Publish product page '+p.id);msg('#publishMsg','পণ্য GitHub-এ সফলভাবে publish হয়েছে।',true);await loadProducts()}catch(e){msg('#publishMsg',e.message)}}
function edit(id){const p=ps.find(x=>x.id===id);if(!p)return;$('#pId').value=p.id;$('#pTitle').value=p.title||'';$('#pCategory').value=p.category||'';$('#pBrand').value=p.brand||'';$('#pSku').value=p.sku||'';$('#pPrice').value=p.price||'';$('#pOldPrice').value=p.oldPrice||'';$('#pStock').value=p.stock||0;$('#pStatus').value=p.status||'published';$('#pShort').value=p.shortDescription||'';$('#pImage').value=p.image||'';$('#pImages').value=(p.images||[]).join('\n');$('#pYoutube').value=(p.youtube||[]).join('\n');$('#pTags').value=(p.tags||[]).join(', ');fetch(p.description+'?v='+Date.now()).then(r=>r.ok?r.text():'').then(t=>$('#pDescription').value=t);go('add')}
function go(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.admin-section').forEach(s=>s.classList.toggle('hidden',s.id!=='tab-'+name))}
async function loadSiteForm(){const s=await readSite();const map={sName:'name',sLogo:'logo',sFavicon:'favicon',sPrimary:'primary',sButton:'button',sButtonText:'buttonText',sBg:'background',sCard:'card',sText:'text',sMuted:'muted',sBorder:'border',sHeroEyebrow:'heroEyebrow',sHeroTitle:'heroTitle',sHeroText:'heroText',sHeroImage:'heroImage',sAnnouncement:'announcement',sCurrency:'currency',sDelivery:'deliveryFee',sWhatsapp:'whatsapp',sPhone:'contactPhone',sFacebook:'facebook',sInstagram:'instagram',sYoutube:'youtube',sFooter:'footerText',sSeoTitle:'seoTitle',sSeoDescription:'seoDescription'};Object.entries(map).forEach(([id,k])=>{const e=$('#'+id);if(e)e.value=s[k]??''});const checks={sShowPrices:'showPrices',sShowCategories:'showCategories',sShowReviews:'showReviews',sShowRelated:'showRelated',sShowVideos:'showVideos',sShowWishlist:'showWishlist'};Object.entries(checks).forEach(([id,k])=>$('#'+id).checked=s[k]!==false);setLogoPreview(s.logo)}
function collectSite(){return{version:5,name:$('#sName').value.trim()||'BanglaBazar',logo:$('#sLogoCropped').value||$('#sLogo').value.trim(),favicon:$('#sFavicon').value.trim(),primary:$('#sPrimary').value,button:$('#sButton').value,buttonText:$('#sButtonText').value,background:$('#sBg').value,card:$('#sCard').value,text:$('#sText').value,muted:$('#sMuted').value,border:$('#sBorder').value,currency:$('#sCurrency').value.trim()||'৳',deliveryFee:Number($('#sDelivery').value||0),showPrices:$('#sShowPrices').checked,showCategories:$('#sShowCategories').checked,showReviews:$('#sShowReviews').checked,showRelated:$('#sShowRelated').checked,showVideos:$('#sShowVideos').checked,showWishlist:$('#sShowWishlist').checked,heroEyebrow:$('#sHeroEyebrow').value.trim(),heroTitle:$('#sHeroTitle').value.trim(),heroText:$('#sHeroText').value.trim(),heroImage:$('#sHeroImage').value.trim(),announcement:$('#sAnnouncement').value.trim(),footerText:$('#sFooter').value.trim(),contactPhone:$('#sPhone').value.trim(),whatsapp:$('#sWhatsapp').value.trim(),facebook:$('#sFacebook').value.trim(),instagram:$('#sInstagram').value.trim(),youtube:$('#sYoutube').value.trim(),seoTitle:$('#sSeoTitle').value.trim(),seoDescription:$('#sSeoDescription').value.trim()}}
async function saveSite(e){e.preventDefault();try{const s=collectSite();await put('data/site.json',JSON.stringify(s,null,2),'Update website settings');localStorage.setItem('bb_site_cache_v5',JSON.stringify(s));msg('#siteMsg','Website settings GitHub-এ publish হয়েছে।',true);BB.applySite(s)}catch(e){msg('#siteMsg',e.message)}}
function setLogoPreview(src){$('#logoPreview').innerHTML=src?`<img src="${esc(src)}" alt="Logo">`:'B'}
function setupLogoCrop(){const file=$('#logoFile'),modal=$('#adminCropModal'),canvas=$('#adminCropCanvas'),zoom=$('#adminCropZoom'),ctx=canvas.getContext('2d');let img=null,scale=1,x=0,y=0,drag=false,sx=0,sy=0,ox=0,oy=0;function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(!img)return;const base=Math.max(canvas.width/img.width,canvas.height/img.height),sc=base*scale,w=img.width*sc,h=img.height*sc;ctx.drawImage(img,(canvas.width-w)/2+x,(canvas.height-h)/2+y,w,h)}function openImage(src){img=new Image();if(/^https?:/i.test(src))img.crossOrigin='anonymous';img.onload=()=>{scale=1;x=y=0;zoom.value=1;draw();modal.classList.remove('hidden')};img.onerror=()=>msg('#siteMsg','Logo image load হয়নি। URL-এর CORS permission না থাকলে remote image crop করা যাবে না।');img.src=src}$('#cropLogoBtn').onclick=()=>{const url=$('#sLogo').value.trim();if(url)openImage(url);else file.click()};file.onchange=()=>file.files[0]&&(()=>{const rd=new FileReader();rd.onload=()=>openImage(rd.result);rd.readAsDataURL(file.files[0])})();zoom.oninput=()=>{scale=Number(zoom.value);draw()};canvas.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;sy=e.clientY;ox=x;oy=y;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){x=ox+e.clientX-sx;y=oy+e.clientY-sy;draw()}});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);$('#adminCropClose').onclick=()=>modal.classList.add('hidden');$('#adminCropCancel').onclick=()=>modal.classList.add('hidden');$('#adminCropApply').onclick=()=>{try{const out=document.createElement('canvas');out.width=700;out.height=420;const c=out.getContext('2d'),base=Math.max(700/img.width,420/img.height),sc=base*scale,w=img.width*sc,h=img.height*sc;c.drawImage(img,(700-w)/2+x*(700/canvas.width),(420-h)/2+y*(420/canvas.width),w,h);const d=out.toDataURL('image/jpeg',.8);$('#sLogoCropped').value=d;setLogoPreview(d);modal.classList.add('hidden')}catch{msg('#siteMsg','এই Logo URL crop করার অনুমতি নেই। একই ছবিটি download করে Admin-এর file picker দিয়ে crop করুন।')}}}
function init(){if(sessionStorage.getItem('bb_admin_ok_v5')==='1')open();$('#adminEnter').onclick=enter;$('#testGithub').onclick=testGithub;$('#saveGithub').onclick=()=>{const g=saveG();if(!g.user||!g.repo||!g.token)return msg('#adminMsg','সব GitHub তথ্য দিন।');msg('#adminMsg','GitHub credentials session-এ save হয়েছে।',true);testGithub()};$('#clearGithub').onclick=()=>{sessionStorage.removeItem(GH);$('#ghToken').value='';msg('#adminMsg','Token clear হয়েছে।')};$('#logoutAdmin').onclick=()=>{sessionStorage.removeItem('bb_admin_ok_v5');location.reload()};$$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#productForm').onsubmit=publish;$('#clearProduct').onclick=()=>$('#productForm').reset();$('#siteForm').onsubmit=saveSite;$('#previewSite').onclick=()=>window.open('index.html','_blank');setupLogoCrop();loadLocal()}
async function enter(){const p=$('#adminPassword').value.trim();if(!p)return msg('#adminMsg','Admin password দিন।');let h=localStorage.getItem(KEY);if(!h){h=await sha(p);localStorage.setItem(KEY,h);sessionStorage.setItem('bb_admin_ok_v5','1');open();return}if(await sha(p)===h){sessionStorage.setItem('bb_admin_ok_v5','1');open()}else msg('#adminMsg','Admin password সঠিক নয়।')}
function open(){$('#adminGate').classList.add('hidden');$('#adminPanel').classList.remove('hidden');loadLocal()}
function loadLocal(){const g=gh();$('#ghUser').value=g.user||'';$('#ghRepo').value=g.repo||'';$('#ghBranch').value=g.branch||'main';loadSiteForm();loadProducts()}
window.BBAdmin={init};
})();